/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as CourseWordImport } from './routes/course.word'
import { Route as CourseAiImport } from './routes/course.ai'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CourseWordRoute = CourseWordImport.update({
  id: '/course/word',
  path: '/course/word',
  getParentRoute: () => rootRoute,
} as any)

const CourseAiRoute = CourseAiImport.update({
  id: '/course/ai',
  path: '/course/ai',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/course/ai': {
      id: '/course/ai'
      path: '/course/ai'
      fullPath: '/course/ai'
      preLoaderRoute: typeof CourseAiImport
      parentRoute: typeof rootRoute
    }
    '/course/word': {
      id: '/course/word'
      path: '/course/word'
      fullPath: '/course/word'
      preLoaderRoute: typeof CourseWordImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/course/ai': typeof CourseAiRoute
  '/course/word': typeof CourseWordRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/course/ai': typeof CourseAiRoute
  '/course/word': typeof CourseWordRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/course/ai': typeof CourseAiRoute
  '/course/word': typeof CourseWordRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/course/ai' | '/course/word'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/course/ai' | '/course/word'
  id: '__root__' | '/' | '/admin' | '/course/ai' | '/course/word'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CourseAiRoute: typeof CourseAiRoute
  CourseWordRoute: typeof CourseWordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CourseAiRoute: CourseAiRoute,
  CourseWordRoute: CourseWordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/course/ai",
        "/course/word"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/course/ai": {
      "filePath": "course.ai.tsx"
    },
    "/course/word": {
      "filePath": "course.word.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
